FROM arm32v7/alpine:latest

ARG SCHEDULE
ARG CRON_SCRIPT

RUN \
	apk update \
	&& apk add \
	python3 \
	curl \
	bash \
	mariadb-client \
	&& pip3 install --upgrade pip \
	&& pip3 install awscli

COPY etc/crontab/root /etc/crontab/root

RUN echo "${SCHEDULE} ${CRON_SCRIPT} 2>&1" >> /etc/crontab/root